### ISSUE TITLE
Machine Type example problematically

### ISSUE THREAD

**Issue by Salandora** [OctoPrint/Plugin-Examples#2]
In the [read_m115_response.py line 10](https://github.com/OctoPrint/Plugin-Examples/blob/master/read_m115_response.py#L10)
the given d.split(':') is problematically and can cause an exception:

Example Response:
`FIRMWARE_NAME:Repetier_1.0.0dev FIRMWARE_URL:https://github.com/repetier/Repetier-Firmware/ PROTOCOL_VERSION:1.0 MACHINE_TYPE:Core_XY EXTRUDER_COUNT:1 REPETIER_PROTOCOL:3`

Important part:
`FIRMWARE_URL:https://github.com/repetier/Repetier-Firmware/ `

as you can see this line contains 2 colons which leads to a split like this:
`["FIRMWARE_NAME", "https", "//github.com/repetier/Repetier-Firmware/"]`

this can't be processed by the dict() and therefore leads to an exception.

proposed change, replace the oneliner with this code or similiar:
```
split_line = line.split(' ')
printer_data = dict()
for d in split_line:
	data = d.split(':')
	printer_data[data[0]] = ':'.join(data[1:])
```

This also affects the wiki entry.

**Comment by foosel** [comment]
A one liner circumventing this issue would be 

    printer_data = dict(d.split(':', 1) for d in line.split(' '))

That would still produce potentially wrong results though in case of something like

    FIRMWARE_NAME:Some Firmware FIRMWARE_AUTHOR:Joe Random Hacker

since it would split on the whitespaces inside the values. I adjusted the example to use OctoPrint's [own parse routine](https://github.com/foosel/OctoPrint/blob/master/src/octoprint/util/comm.py#L2967-L2985) that is included since 1.3.0 and uses a repeatedly used regular expression.
